## 利用GitHub Actions每天定时给百度推送链接，提高收录率 ##

name: baiduPush

# 两种触发方式：一、push代码，二、每天国际标准时间23点（北京时间+8即早上7点）运行
# on:
#   push:
#   schedule:
#     - cron: '0 23 * * *' # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule


env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）
  SERVER_IP: '123456789' # 远程服务器IP
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  BAIDU_PUSH_TOKEN: ${{ secrets.BAIDU_PUSH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/5 * * * *' # 每5分钟一次，测试用



jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run baiduPush' # 步骤二，执行sh命令文件
        run:  echo "aa" && echo 'Hi ${{ env.SERVER_IP }}' # 运行目录是仓库根目录
